# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1afcacf401da919d55576d86a1918c5528f61c9fc8654dda119ac23f397f37f951d7ede7b8f588b3e8a6c273504fbae073a0c73ea7e96f1baba92a4dd6ae3c3a

test:
  secret_key_base: 69195a4e80925e3c8cca030e740568bc1eaab43ae8e1f89f74c0784024ef6380723fa2cc646196135ad436b89ceeb71e7820df6c7b326094591a053cc28199c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
